services:
  mongodb:
    image: mongodb:1
    container_name: mongodb
    networks:
      - roboshop

  web:
    image: web:latest
    container_name: web
    ports:
      - "80:80"
    depends_on:
      - catalogue
    networks:
      - roboshop

  catalogue:
    image: catalogue:1
    container_name: catalogue
    ports:
      - "8081:8080"
    networks:
      - roboshop

networks:
  roboshop:
    driver: bridge
